# Generated by Django 2.2.4 on 2019-08-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='手机号')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('sex', models.BooleanField(choices=[(False, '女'), (True, '男')], default=None, null=True, verbose_name='性别')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='客户')),
                ('wxname', models.CharField(blank=True, default='', max_length=32, verbose_name='微信名')),
                ('openid', models.CharField(max_length=32, unique=True, verbose_name='openid')),
                ('apikey', models.CharField(max_length=20, verbose_name='接口密钥')),
            ],
            options={
                'verbose_name': '游客列表',
                'verbose_name_plural': '游客列表',
                'db_table': 'tour_user',
            },
        ),
    ]
