# Generated by Django 2.2.4 on 2019-08-20 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190813_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], verbose_name='会员等级')),
                ('num', models.IntegerField(verbose_name='课时')),
                ('price', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='价格')),
                ('pay_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'group_card',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='目录名称')),
                ('time', models.IntegerField(default=60, verbose_name='时长/min')),
                ('price', models.IntegerField(default=1, verbose_name='价格/课时')),
                ('sale', models.IntegerField(default=0, verbose_name='销量')),
            ],
            options={
                'verbose_name': '目录',
                'verbose_name_plural': '目录',
                'db_table': 'group_list',
            },
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类别')),
            ],
            options={
                'verbose_name': '课程类型',
                'verbose_name_plural': '课程类型',
                'db_table': 'group_sort',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='手机号')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('sex', models.BooleanField(choices=[(False, '女'), (True, '男')], default=None, null=True, verbose_name='性别')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='姓名')),
                ('wx_name', models.CharField(blank=True, default='', max_length=32, verbose_name='微信名')),
                ('mail', models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('wx_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信号')),
                ('openid', models.CharField(max_length=32, unique=True, verbose_name='openid')),
                ('key', models.CharField(max_length=50, verbose_name='接口密钥')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'db_table': 'group_teacher',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '客户', 'verbose_name_plural': '客户'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='apikey',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='wxname',
            new_name='wx_name',
        ),
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='wx_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='姓名'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='group_user',
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=200, null=True, verbose_name='文本介绍')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserDetail', to='app.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户详情',
                'verbose_name_plural': '用户详情',
                'db_table': 'group_user_detail',
            },
        ),
        migrations.CreateModel(
            name='UAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=50, null=True, verbose_name='账号')),
                ('pwd', models.CharField(blank=True, max_length=50, null=True, verbose_name='密码')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='UAccount', to='app.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户classin',
                'verbose_name_plural': '用户classin',
                'db_table': 'group_user_account',
            },
        ),
        migrations.CreateModel(
            name='TchDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=200, null=True, verbose_name='文本介绍')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TchDetail', to='app.Teacher', verbose_name='教师')),
            ],
            options={
                'verbose_name': '教师详情',
                'verbose_name_plural': '教师详情',
                'db_table': 'group_tch_detail',
            },
        ),
        migrations.CreateModel(
            name='TAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=50, null=True, verbose_name='账号')),
                ('pwd', models.CharField(blank=True, max_length=50, null=True, verbose_name='密码')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TAccount', to='app.Teacher', verbose_name='教师')),
            ],
            options={
                'verbose_name': '教师classin',
                'verbose_name_plural': '教师classin',
                'db_table': 'group_teacher_account',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名')),
                ('main', models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='主图')),
                ('sort', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Subject', to='app.Sort', verbose_name='类别')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'group_subject',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='实付/课时')),
                ('status', models.IntegerField(choices=[(0, '评课中'), (1, '评课成功'), (2, '已完成'), (3, '上课失败')], default=0, verbose_name='状态')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='时间')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Order_list', to='app.List', verbose_name='目录')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Order_partner', to='app.User', verbose_name='伙伴')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Order_sub', to='app.Subject', verbose_name='课程')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Order_teacher', to='app.User', verbose_name='教师')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Order_user', to='app.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'group_order',
            },
        ),
        migrations.AddField(
            model_name='list',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='List', to='app.Subject', verbose_name='课程'),
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=200, null=True, verbose_name='文本介绍')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Detail', to='app.Subject', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程详情',
                'verbose_name_plural': '课程详情',
                'db_table': 'group_detail',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='评论内容')),
                ('tch', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5, verbose_name='教师评分')),
                ('sub', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5, verbose_name='课程评分')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Comment_user', to='app.List', verbose_name='目录')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Comment_comment', to='app.Order', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Comment_order', to='app.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'group_comment',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='海报')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Banner', to='app.Subject', verbose_name='课程')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banner',
                'db_table': 'group_banner',
            },
        ),
    ]
