# Generated by Django 2.2.4 on 2019-08-20 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190820_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taccount',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Teacher', verbose_name='教师'),
        ),
    ]
