# Generated by Django 2.2.4 on 2019-08-20 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190820_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Subject', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Subject', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='list',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Subject', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Sort', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='uaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User', verbose_name='用户'),
        ),
    ]
