# Generated by Django 2.2.4 on 2019-08-20 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190820_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=False, verbose_name='是否生效')),
                ('reward', models.IntegerField(default=0, verbose_name='奖励/课时')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_user', to='app.User', verbose_name='发起邀请者')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Relation_user', to='app.User', verbose_name='被邀请者')),
            ],
            options={
                'verbose_name': '用户关系',
                'verbose_name_plural': '用户关系',
                'db_table': 'group_relation',
            },
        ),
    ]
