# Generated by Django 2.2.4 on 2019-08-20 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='pay_time',
            new_name='created',
        ),
        migrations.CreateModel(
            name='COrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(max_length=20, unique=True, verbose_name='订单号')),
                ('tradeNo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='交易号')),
                ('payNoti', models.SmallIntegerField(choices=[(0, '未通知'), (1, '通知成功'), (2, '通知失败'), (3, '查询支付成功')], default=0, verbose_name='支付通知状态')),
                ('userId', models.BigIntegerField(verbose_name='用户ID')),
                ('Fee', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='实付金额')),
                ('status', models.SmallIntegerField(choices=[(0, '已关闭'), (1, '已支付')], default=0, verbose_name='订单状态')),
                ('payTime', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Card', verbose_name='会员卡')),
            ],
            options={
                'verbose_name': '会员卡订单',
                'verbose_name_plural': '会员卡订单',
                'db_table': 'group_card_order',
            },
        ),
    ]
